version: "3.7"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - srcs_mariadb_data:/var/lib/mysql
      - ./tools/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wordpress_net
    restart: always

  nginx:
    build: ./requirements/nginx
    env_file:
      - ./.env
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    networks:
      - wordpress_net

volumes:
  wordpress_data:
  mariadb_data:
  srcs_mariadb_data:

networks:
  wordpress_net:
    driver: bridge
